# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160521_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Crédito', to='core.Item')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Débito', to='core.Item')),
            ],
            options={
                'verbose_name_plural': 'Transações',
                'verbose_name': 'Transação',
            },
        ),
    ]
