# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Crédito', to='core.Item', verbose_name='Crédito'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Débito', to='core.Item', verbose_name='Débito'),
        ),
    ]
