# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160521_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='core.Item', verbose_name='Crédito'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='core.Item', verbose_name='Débito'),
        ),
    ]
